# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import owl_client.client.Interfaces.grpc_client.robot_service_pb2 as robot__service__pb2


class RobotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/robot_service.RobotService/Ping',
                request_serializer=robot__service__pb2.PingRequest.SerializeToString,
                response_deserializer=robot__service__pb2.PingResponse.FromString,
                )
        self.SetPayloadMass = channel.unary_unary(
                '/robot_service.RobotService/SetPayloadMass',
                request_serializer=robot__service__pb2.SetPayloadMassRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetPayloadMassResponse.FromString,
                )
        self.SetPayloadCOG = channel.unary_unary(
                '/robot_service.RobotService/SetPayloadCOG',
                request_serializer=robot__service__pb2.SetPayloadCOGLoadRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetPayloadCOGResponse.FromString,
                )
        self.SetPayloadInertiaMatrix = channel.unary_unary(
                '/robot_service.RobotService/SetPayloadInertiaMatrix',
                request_serializer=robot__service__pb2.SetPayloadInertiaMatrixRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetPayloadInertiaMatrixResponse.FromString,
                )
        self.SetPayload = channel.unary_unary(
                '/robot_service.RobotService/SetPayload',
                request_serializer=robot__service__pb2.SetPayloadRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetPayloadResponse.FromString,
                )
        self.SetTCP = channel.unary_unary(
                '/robot_service.RobotService/SetTCP',
                request_serializer=robot__service__pb2.SetTCPRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetTCPResponse.FromString,
                )
        self.SetGravityVector = channel.unary_unary(
                '/robot_service.RobotService/SetGravityVector',
                request_serializer=robot__service__pb2.SetGravityVectorRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetGravityVectorResponse.FromString,
                )
        self.SetCartesianJoggingFrame = channel.unary_unary(
                '/robot_service.RobotService/SetCartesianJoggingFrame',
                request_serializer=robot__service__pb2.SetCartesianJoggingFrameRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetCartesianJoggingFrameResponse.FromString,
                )
        self.SetDigitalOutput = channel.unary_unary(
                '/robot_service.RobotService/SetDigitalOutput',
                request_serializer=robot__service__pb2.SetDigitalOutputRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetDigitalOutputResponse.FromString,
                )
        self.SetDefaultProgram = channel.unary_unary(
                '/robot_service.RobotService/SetDefaultProgram',
                request_serializer=robot__service__pb2.SetDefaultProgramRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetDefaultProgramResponse.FromString,
                )
        self.SetDefaultHome = channel.unary_unary(
                '/robot_service.RobotService/SetDefaultHome',
                request_serializer=robot__service__pb2.SetDefaultHomeRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetDefaultHomeResponse.FromString,
                )
        self.SetSpeedFraction = channel.unary_unary(
                '/robot_service.RobotService/SetSpeedFraction',
                request_serializer=robot__service__pb2.SetSpeedFractionRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetSpeedFractionResponse.FromString,
                )
        self.SetDefaultConfiguration = channel.unary_unary(
                '/robot_service.RobotService/SetDefaultConfiguration',
                request_serializer=robot__service__pb2.SetDefaultConfigurationRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetDefaultConfigurationResponse.FromString,
                )
        self.SetActiveConfiguration = channel.unary_unary(
                '/robot_service.RobotService/SetActiveConfiguration',
                request_serializer=robot__service__pb2.SetActiveConfigurationRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SetActiveConfigurationResponse.FromString,
                )
        self.GetPayloadInertiaMatrix = channel.unary_unary(
                '/robot_service.RobotService/GetPayloadInertiaMatrix',
                request_serializer=robot__service__pb2.GetPayloadInertiaMatrixRequest.SerializeToString,
                response_deserializer=robot__service__pb2.GetPayloadInertiaMatrixResponse.FromString,
                )
        self.GetActiveConfiguration = channel.unary_unary(
                '/robot_service.RobotService/GetActiveConfiguration',
                request_serializer=robot__service__pb2.GetActiveConfigurationRequest.SerializeToString,
                response_deserializer=robot__service__pb2.GetActiveConfigurationResponse.FromString,
                )
        self.GetDefaultConfiguration = channel.unary_unary(
                '/robot_service.RobotService/GetDefaultConfiguration',
                request_serializer=robot__service__pb2.GetDefaultConfigurationRequest.SerializeToString,
                response_deserializer=robot__service__pb2.GetDefaultConfigurationResponse.FromString,
                )
        self.GetVersion = channel.unary_unary(
                '/robot_service.RobotService/GetVersion',
                request_serializer=robot__service__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=robot__service__pb2.GetVersionResponse.FromString,
                )
        self.PowerOn = channel.unary_unary(
                '/robot_service.RobotService/PowerOn',
                request_serializer=robot__service__pb2.PowerOnRequest.SerializeToString,
                response_deserializer=robot__service__pb2.PowerOnResponse.FromString,
                )
        self.PowerDown = channel.unary_unary(
                '/robot_service.RobotService/PowerDown',
                request_serializer=robot__service__pb2.PowerDownRequest.SerializeToString,
                response_deserializer=robot__service__pb2.PowerDownResponse.FromString,
                )
        self.EnterTeachMode = channel.unary_unary(
                '/robot_service.RobotService/EnterTeachMode',
                request_serializer=robot__service__pb2.EnterTeachModeRequest.SerializeToString,
                response_deserializer=robot__service__pb2.EnterTeachModeResponse.FromString,
                )
        self.ExitTeachMode = channel.unary_unary(
                '/robot_service.RobotService/ExitTeachMode',
                request_serializer=robot__service__pb2.ExitTeachModeRequest.SerializeToString,
                response_deserializer=robot__service__pb2.ExitTeachModeResponse.FromString,
                )
        self.FKRequest = channel.unary_unary(
                '/robot_service.RobotService/FKRequest',
                request_serializer=robot__service__pb2.FKRequestRequest.SerializeToString,
                response_deserializer=robot__service__pb2.FKRequestResponse.FromString,
                )
        self.IKRequest = channel.unary_unary(
                '/robot_service.RobotService/IKRequest',
                request_serializer=robot__service__pb2.IKRequestRequest.SerializeToString,
                response_deserializer=robot__service__pb2.IKRequestResponse.FromString,
                )
        self.SendScript = channel.unary_unary(
                '/robot_service.RobotService/SendScript',
                request_serializer=robot__service__pb2.SendScriptRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SendScriptResponse.FromString,
                )
        self.SendOperatorAssignment = channel.unary_unary(
                '/robot_service.RobotService/SendOperatorAssignment',
                request_serializer=robot__service__pb2.SendOperatorAssignmentRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SendOperatorAssignmentResponse.FromString,
                )
        self.PauseScript = channel.unary_unary(
                '/robot_service.RobotService/PauseScript',
                request_serializer=robot__service__pb2.PauseScriptRequest.SerializeToString,
                response_deserializer=robot__service__pb2.PauseScriptResponse.FromString,
                )
        self.ResumeScript = channel.unary_unary(
                '/robot_service.RobotService/ResumeScript',
                request_serializer=robot__service__pb2.ResumeScriptRequest.SerializeToString,
                response_deserializer=robot__service__pb2.ResumeScriptResponse.FromString,
                )
        self.StopScript = channel.unary_unary(
                '/robot_service.RobotService/StopScript',
                request_serializer=robot__service__pb2.StopScriptRequest.SerializeToString,
                response_deserializer=robot__service__pb2.StopScriptResponse.FromString,
                )
        self.MoveToPose = channel.unary_unary(
                '/robot_service.RobotService/MoveToPose',
                request_serializer=robot__service__pb2.MoveToPoseRequest.SerializeToString,
                response_deserializer=robot__service__pb2.MoveToPoseResponse.FromString,
                )
        self.MoveToJoint = channel.unary_unary(
                '/robot_service.RobotService/MoveToJoint',
                request_serializer=robot__service__pb2.MoveToJointRequest.SerializeToString,
                response_deserializer=robot__service__pb2.MoveToJointResponse.FromString,
                )
        self.MovePoses = channel.unary_unary(
                '/robot_service.RobotService/MovePoses',
                request_serializer=robot__service__pb2.MovePosesRequest.SerializeToString,
                response_deserializer=robot__service__pb2.MovePosesResponse.FromString,
                )
        self.MoveTrajectory = channel.unary_unary(
                '/robot_service.RobotService/MoveTrajectory',
                request_serializer=robot__service__pb2.MoveTrajectoryRequest.SerializeToString,
                response_deserializer=robot__service__pb2.MoveTrajectoryResponse.FromString,
                )
        self.MovePause = channel.unary_unary(
                '/robot_service.RobotService/MovePause',
                request_serializer=robot__service__pb2.MovePauseRequest.SerializeToString,
                response_deserializer=robot__service__pb2.MovePauseResponse.FromString,
                )
        self.MoveResume = channel.unary_unary(
                '/robot_service.RobotService/MoveResume',
                request_serializer=robot__service__pb2.MoveResumeRequest.SerializeToString,
                response_deserializer=robot__service__pb2.MoveResumeResponse.FromString,
                )
        self.MoveAbort = channel.unary_unary(
                '/robot_service.RobotService/MoveAbort',
                request_serializer=robot__service__pb2.MoveAbortRequest.SerializeToString,
                response_deserializer=robot__service__pb2.MoveAbortResponse.FromString,
                )
        self.Configure = channel.unary_unary(
                '/robot_service.RobotService/Configure',
                request_serializer=robot__service__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=robot__service__pb2.ConfigureResponse.FromString,
                )
        self.DoneCallibration = channel.unary_unary(
                '/robot_service.RobotService/DoneCallibration',
                request_serializer=robot__service__pb2.DoneCallibrationRequest.SerializeToString,
                response_deserializer=robot__service__pb2.DoneCallibrationResponse.FromString,
                )
        self.ResetCallibration = channel.unary_unary(
                '/robot_service.RobotService/ResetCallibration',
                request_serializer=robot__service__pb2.ResetCallibrationRequest.SerializeToString,
                response_deserializer=robot__service__pb2.ResetCallibrationResponse.FromString,
                )
        self.SystemUpdate = channel.unary_unary(
                '/robot_service.RobotService/SystemUpdate',
                request_serializer=robot__service__pb2.SystemUpdateRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SystemUpdateResponse.FromString,
                )
        self.SystemEnable = channel.unary_unary(
                '/robot_service.RobotService/SystemEnable',
                request_serializer=robot__service__pb2.SystemEnableRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SystemEnableResponse.FromString,
                )
        self.SystemDisable = channel.unary_unary(
                '/robot_service.RobotService/SystemDisable',
                request_serializer=robot__service__pb2.SystemDisableRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SystemDisableResponse.FromString,
                )
        self.SystemReboot = channel.unary_unary(
                '/robot_service.RobotService/SystemReboot',
                request_serializer=robot__service__pb2.SystemRebootRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SystemRebootResponse.FromString,
                )
        self.SystemShutdown = channel.unary_unary(
                '/robot_service.RobotService/SystemShutdown',
                request_serializer=robot__service__pb2.SystemShutdownRequest.SerializeToString,
                response_deserializer=robot__service__pb2.SystemShutdownResponse.FromString,
                )


class RobotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPayloadMass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPayloadCOG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPayloadInertiaMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPayload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTCP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGravityVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCartesianJoggingFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDigitalOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultProgram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpeedFraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActiveConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayloadInertiaMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefaultConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PowerOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PowerDown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnterTeachMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitTeachMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FKRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IKRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOperatorAssignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToJoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MovePoses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveTrajectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MovePause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveAbort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoneCallibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetCallibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemEnable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemDisable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemReboot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemShutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=robot__service__pb2.PingRequest.FromString,
                    response_serializer=robot__service__pb2.PingResponse.SerializeToString,
            ),
            'SetPayloadMass': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPayloadMass,
                    request_deserializer=robot__service__pb2.SetPayloadMassRequest.FromString,
                    response_serializer=robot__service__pb2.SetPayloadMassResponse.SerializeToString,
            ),
            'SetPayloadCOG': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPayloadCOG,
                    request_deserializer=robot__service__pb2.SetPayloadCOGLoadRequest.FromString,
                    response_serializer=robot__service__pb2.SetPayloadCOGResponse.SerializeToString,
            ),
            'SetPayloadInertiaMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPayloadInertiaMatrix,
                    request_deserializer=robot__service__pb2.SetPayloadInertiaMatrixRequest.FromString,
                    response_serializer=robot__service__pb2.SetPayloadInertiaMatrixResponse.SerializeToString,
            ),
            'SetPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPayload,
                    request_deserializer=robot__service__pb2.SetPayloadRequest.FromString,
                    response_serializer=robot__service__pb2.SetPayloadResponse.SerializeToString,
            ),
            'SetTCP': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTCP,
                    request_deserializer=robot__service__pb2.SetTCPRequest.FromString,
                    response_serializer=robot__service__pb2.SetTCPResponse.SerializeToString,
            ),
            'SetGravityVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGravityVector,
                    request_deserializer=robot__service__pb2.SetGravityVectorRequest.FromString,
                    response_serializer=robot__service__pb2.SetGravityVectorResponse.SerializeToString,
            ),
            'SetCartesianJoggingFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCartesianJoggingFrame,
                    request_deserializer=robot__service__pb2.SetCartesianJoggingFrameRequest.FromString,
                    response_serializer=robot__service__pb2.SetCartesianJoggingFrameResponse.SerializeToString,
            ),
            'SetDigitalOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDigitalOutput,
                    request_deserializer=robot__service__pb2.SetDigitalOutputRequest.FromString,
                    response_serializer=robot__service__pb2.SetDigitalOutputResponse.SerializeToString,
            ),
            'SetDefaultProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultProgram,
                    request_deserializer=robot__service__pb2.SetDefaultProgramRequest.FromString,
                    response_serializer=robot__service__pb2.SetDefaultProgramResponse.SerializeToString,
            ),
            'SetDefaultHome': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultHome,
                    request_deserializer=robot__service__pb2.SetDefaultHomeRequest.FromString,
                    response_serializer=robot__service__pb2.SetDefaultHomeResponse.SerializeToString,
            ),
            'SetSpeedFraction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeedFraction,
                    request_deserializer=robot__service__pb2.SetSpeedFractionRequest.FromString,
                    response_serializer=robot__service__pb2.SetSpeedFractionResponse.SerializeToString,
            ),
            'SetDefaultConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultConfiguration,
                    request_deserializer=robot__service__pb2.SetDefaultConfigurationRequest.FromString,
                    response_serializer=robot__service__pb2.SetDefaultConfigurationResponse.SerializeToString,
            ),
            'SetActiveConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActiveConfiguration,
                    request_deserializer=robot__service__pb2.SetActiveConfigurationRequest.FromString,
                    response_serializer=robot__service__pb2.SetActiveConfigurationResponse.SerializeToString,
            ),
            'GetPayloadInertiaMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayloadInertiaMatrix,
                    request_deserializer=robot__service__pb2.GetPayloadInertiaMatrixRequest.FromString,
                    response_serializer=robot__service__pb2.GetPayloadInertiaMatrixResponse.SerializeToString,
            ),
            'GetActiveConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveConfiguration,
                    request_deserializer=robot__service__pb2.GetActiveConfigurationRequest.FromString,
                    response_serializer=robot__service__pb2.GetActiveConfigurationResponse.SerializeToString,
            ),
            'GetDefaultConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefaultConfiguration,
                    request_deserializer=robot__service__pb2.GetDefaultConfigurationRequest.FromString,
                    response_serializer=robot__service__pb2.GetDefaultConfigurationResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=robot__service__pb2.GetVersionRequest.FromString,
                    response_serializer=robot__service__pb2.GetVersionResponse.SerializeToString,
            ),
            'PowerOn': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerOn,
                    request_deserializer=robot__service__pb2.PowerOnRequest.FromString,
                    response_serializer=robot__service__pb2.PowerOnResponse.SerializeToString,
            ),
            'PowerDown': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerDown,
                    request_deserializer=robot__service__pb2.PowerDownRequest.FromString,
                    response_serializer=robot__service__pb2.PowerDownResponse.SerializeToString,
            ),
            'EnterTeachMode': grpc.unary_unary_rpc_method_handler(
                    servicer.EnterTeachMode,
                    request_deserializer=robot__service__pb2.EnterTeachModeRequest.FromString,
                    response_serializer=robot__service__pb2.EnterTeachModeResponse.SerializeToString,
            ),
            'ExitTeachMode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitTeachMode,
                    request_deserializer=robot__service__pb2.ExitTeachModeRequest.FromString,
                    response_serializer=robot__service__pb2.ExitTeachModeResponse.SerializeToString,
            ),
            'FKRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.FKRequest,
                    request_deserializer=robot__service__pb2.FKRequestRequest.FromString,
                    response_serializer=robot__service__pb2.FKRequestResponse.SerializeToString,
            ),
            'IKRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.IKRequest,
                    request_deserializer=robot__service__pb2.IKRequestRequest.FromString,
                    response_serializer=robot__service__pb2.IKRequestResponse.SerializeToString,
            ),
            'SendScript': grpc.unary_unary_rpc_method_handler(
                    servicer.SendScript,
                    request_deserializer=robot__service__pb2.SendScriptRequest.FromString,
                    response_serializer=robot__service__pb2.SendScriptResponse.SerializeToString,
            ),
            'SendOperatorAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOperatorAssignment,
                    request_deserializer=robot__service__pb2.SendOperatorAssignmentRequest.FromString,
                    response_serializer=robot__service__pb2.SendOperatorAssignmentResponse.SerializeToString,
            ),
            'PauseScript': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseScript,
                    request_deserializer=robot__service__pb2.PauseScriptRequest.FromString,
                    response_serializer=robot__service__pb2.PauseScriptResponse.SerializeToString,
            ),
            'ResumeScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeScript,
                    request_deserializer=robot__service__pb2.ResumeScriptRequest.FromString,
                    response_serializer=robot__service__pb2.ResumeScriptResponse.SerializeToString,
            ),
            'StopScript': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScript,
                    request_deserializer=robot__service__pb2.StopScriptRequest.FromString,
                    response_serializer=robot__service__pb2.StopScriptResponse.SerializeToString,
            ),
            'MoveToPose': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToPose,
                    request_deserializer=robot__service__pb2.MoveToPoseRequest.FromString,
                    response_serializer=robot__service__pb2.MoveToPoseResponse.SerializeToString,
            ),
            'MoveToJoint': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToJoint,
                    request_deserializer=robot__service__pb2.MoveToJointRequest.FromString,
                    response_serializer=robot__service__pb2.MoveToJointResponse.SerializeToString,
            ),
            'MovePoses': grpc.unary_unary_rpc_method_handler(
                    servicer.MovePoses,
                    request_deserializer=robot__service__pb2.MovePosesRequest.FromString,
                    response_serializer=robot__service__pb2.MovePosesResponse.SerializeToString,
            ),
            'MoveTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveTrajectory,
                    request_deserializer=robot__service__pb2.MoveTrajectoryRequest.FromString,
                    response_serializer=robot__service__pb2.MoveTrajectoryResponse.SerializeToString,
            ),
            'MovePause': grpc.unary_unary_rpc_method_handler(
                    servicer.MovePause,
                    request_deserializer=robot__service__pb2.MovePauseRequest.FromString,
                    response_serializer=robot__service__pb2.MovePauseResponse.SerializeToString,
            ),
            'MoveResume': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveResume,
                    request_deserializer=robot__service__pb2.MoveResumeRequest.FromString,
                    response_serializer=robot__service__pb2.MoveResumeResponse.SerializeToString,
            ),
            'MoveAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveAbort,
                    request_deserializer=robot__service__pb2.MoveAbortRequest.FromString,
                    response_serializer=robot__service__pb2.MoveAbortResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=robot__service__pb2.ConfigureRequest.FromString,
                    response_serializer=robot__service__pb2.ConfigureResponse.SerializeToString,
            ),
            'DoneCallibration': grpc.unary_unary_rpc_method_handler(
                    servicer.DoneCallibration,
                    request_deserializer=robot__service__pb2.DoneCallibrationRequest.FromString,
                    response_serializer=robot__service__pb2.DoneCallibrationResponse.SerializeToString,
            ),
            'ResetCallibration': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetCallibration,
                    request_deserializer=robot__service__pb2.ResetCallibrationRequest.FromString,
                    response_serializer=robot__service__pb2.ResetCallibrationResponse.SerializeToString,
            ),
            'SystemUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemUpdate,
                    request_deserializer=robot__service__pb2.SystemUpdateRequest.FromString,
                    response_serializer=robot__service__pb2.SystemUpdateResponse.SerializeToString,
            ),
            'SystemEnable': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemEnable,
                    request_deserializer=robot__service__pb2.SystemEnableRequest.FromString,
                    response_serializer=robot__service__pb2.SystemEnableResponse.SerializeToString,
            ),
            'SystemDisable': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemDisable,
                    request_deserializer=robot__service__pb2.SystemDisableRequest.FromString,
                    response_serializer=robot__service__pb2.SystemDisableResponse.SerializeToString,
            ),
            'SystemReboot': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemReboot,
                    request_deserializer=robot__service__pb2.SystemRebootRequest.FromString,
                    response_serializer=robot__service__pb2.SystemRebootResponse.SerializeToString,
            ),
            'SystemShutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemShutdown,
                    request_deserializer=robot__service__pb2.SystemShutdownRequest.FromString,
                    response_serializer=robot__service__pb2.SystemShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_service.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/Ping',
            robot__service__pb2.PingRequest.SerializeToString,
            robot__service__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPayloadMass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetPayloadMass',
            robot__service__pb2.SetPayloadMassRequest.SerializeToString,
            robot__service__pb2.SetPayloadMassResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPayloadCOG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetPayloadCOG',
            robot__service__pb2.SetPayloadCOGLoadRequest.SerializeToString,
            robot__service__pb2.SetPayloadCOGResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPayloadInertiaMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetPayloadInertiaMatrix',
            robot__service__pb2.SetPayloadInertiaMatrixRequest.SerializeToString,
            robot__service__pb2.SetPayloadInertiaMatrixResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetPayload',
            robot__service__pb2.SetPayloadRequest.SerializeToString,
            robot__service__pb2.SetPayloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTCP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetTCP',
            robot__service__pb2.SetTCPRequest.SerializeToString,
            robot__service__pb2.SetTCPResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetGravityVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetGravityVector',
            robot__service__pb2.SetGravityVectorRequest.SerializeToString,
            robot__service__pb2.SetGravityVectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCartesianJoggingFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetCartesianJoggingFrame',
            robot__service__pb2.SetCartesianJoggingFrameRequest.SerializeToString,
            robot__service__pb2.SetCartesianJoggingFrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDigitalOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetDigitalOutput',
            robot__service__pb2.SetDigitalOutputRequest.SerializeToString,
            robot__service__pb2.SetDigitalOutputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDefaultProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetDefaultProgram',
            robot__service__pb2.SetDefaultProgramRequest.SerializeToString,
            robot__service__pb2.SetDefaultProgramResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDefaultHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetDefaultHome',
            robot__service__pb2.SetDefaultHomeRequest.SerializeToString,
            robot__service__pb2.SetDefaultHomeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSpeedFraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetSpeedFraction',
            robot__service__pb2.SetSpeedFractionRequest.SerializeToString,
            robot__service__pb2.SetSpeedFractionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDefaultConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetDefaultConfiguration',
            robot__service__pb2.SetDefaultConfigurationRequest.SerializeToString,
            robot__service__pb2.SetDefaultConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetActiveConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SetActiveConfiguration',
            robot__service__pb2.SetActiveConfigurationRequest.SerializeToString,
            robot__service__pb2.SetActiveConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPayloadInertiaMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/GetPayloadInertiaMatrix',
            robot__service__pb2.GetPayloadInertiaMatrixRequest.SerializeToString,
            robot__service__pb2.GetPayloadInertiaMatrixResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActiveConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/GetActiveConfiguration',
            robot__service__pb2.GetActiveConfigurationRequest.SerializeToString,
            robot__service__pb2.GetActiveConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDefaultConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/GetDefaultConfiguration',
            robot__service__pb2.GetDefaultConfigurationRequest.SerializeToString,
            robot__service__pb2.GetDefaultConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/GetVersion',
            robot__service__pb2.GetVersionRequest.SerializeToString,
            robot__service__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PowerOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/PowerOn',
            robot__service__pb2.PowerOnRequest.SerializeToString,
            robot__service__pb2.PowerOnResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PowerDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/PowerDown',
            robot__service__pb2.PowerDownRequest.SerializeToString,
            robot__service__pb2.PowerDownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnterTeachMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/EnterTeachMode',
            robot__service__pb2.EnterTeachModeRequest.SerializeToString,
            robot__service__pb2.EnterTeachModeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitTeachMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/ExitTeachMode',
            robot__service__pb2.ExitTeachModeRequest.SerializeToString,
            robot__service__pb2.ExitTeachModeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FKRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/FKRequest',
            robot__service__pb2.FKRequestRequest.SerializeToString,
            robot__service__pb2.FKRequestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IKRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/IKRequest',
            robot__service__pb2.IKRequestRequest.SerializeToString,
            robot__service__pb2.IKRequestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SendScript',
            robot__service__pb2.SendScriptRequest.SerializeToString,
            robot__service__pb2.SendScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendOperatorAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SendOperatorAssignment',
            robot__service__pb2.SendOperatorAssignmentRequest.SerializeToString,
            robot__service__pb2.SendOperatorAssignmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PauseScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/PauseScript',
            robot__service__pb2.PauseScriptRequest.SerializeToString,
            robot__service__pb2.PauseScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResumeScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/ResumeScript',
            robot__service__pb2.ResumeScriptRequest.SerializeToString,
            robot__service__pb2.ResumeScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/StopScript',
            robot__service__pb2.StopScriptRequest.SerializeToString,
            robot__service__pb2.StopScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveToPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/MoveToPose',
            robot__service__pb2.MoveToPoseRequest.SerializeToString,
            robot__service__pb2.MoveToPoseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveToJoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/MoveToJoint',
            robot__service__pb2.MoveToJointRequest.SerializeToString,
            robot__service__pb2.MoveToJointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MovePoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/MovePoses',
            robot__service__pb2.MovePosesRequest.SerializeToString,
            robot__service__pb2.MovePosesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/MoveTrajectory',
            robot__service__pb2.MoveTrajectoryRequest.SerializeToString,
            robot__service__pb2.MoveTrajectoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MovePause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/MovePause',
            robot__service__pb2.MovePauseRequest.SerializeToString,
            robot__service__pb2.MovePauseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/MoveResume',
            robot__service__pb2.MoveResumeRequest.SerializeToString,
            robot__service__pb2.MoveResumeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/MoveAbort',
            robot__service__pb2.MoveAbortRequest.SerializeToString,
            robot__service__pb2.MoveAbortResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/Configure',
            robot__service__pb2.ConfigureRequest.SerializeToString,
            robot__service__pb2.ConfigureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoneCallibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/DoneCallibration',
            robot__service__pb2.DoneCallibrationRequest.SerializeToString,
            robot__service__pb2.DoneCallibrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetCallibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/ResetCallibration',
            robot__service__pb2.ResetCallibrationRequest.SerializeToString,
            robot__service__pb2.ResetCallibrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SystemUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SystemUpdate',
            robot__service__pb2.SystemUpdateRequest.SerializeToString,
            robot__service__pb2.SystemUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SystemEnable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SystemEnable',
            robot__service__pb2.SystemEnableRequest.SerializeToString,
            robot__service__pb2.SystemEnableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SystemDisable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SystemDisable',
            robot__service__pb2.SystemDisableRequest.SerializeToString,
            robot__service__pb2.SystemDisableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SystemReboot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SystemReboot',
            robot__service__pb2.SystemRebootRequest.SerializeToString,
            robot__service__pb2.SystemRebootResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SystemShutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_service.RobotService/SystemShutdown',
            robot__service__pb2.SystemShutdownRequest.SerializeToString,
            robot__service__pb2.SystemShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
